name: mgym
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - gymnasium
      - stable-baselines3
      - tqdm
      - numpy
      - tensorboard
      - salabim
